import React, { useState, useEffect, useMemo } from 'react';
import { DamlLedger, useParty, useLedger, useStreamQueries, ContractId } from '@c7/react';

// Assuming the codegen output is in this location.
// In a real project, this would be generated by `dpm codegen-js`.
// We're making reasonable assumptions about the Daml models.
import {
  Subscription,
  Invoice,
  Cancellation
} from '@daml.js/canton-subscription-billing-0.1.0/lib/Model';
import { InvoiceList } from './InvoiceList';

import './App.css';

const App: React.FC = () => {
  const [credentials, setCredentials] = useState<{ token: string; party: string } | undefined>();

  useEffect(() => {
    // For development convenience, try to load credentials from local storage
    const savedToken = localStorage.getItem('daml.token');
    const savedParty = localStorage.getItem('daml.party');
    if (savedToken && savedParty) {
      setCredentials({ token: savedToken, party: savedParty });
    }
  }, []);

  const handleLogin = (token: string, party: string) => {
    localStorage.setItem('daml.token', token);
    localStorage.setItem('daml.party', party);
    setCredentials({ token, party });
  };

  const handleLogout = () => {
    localStorage.removeItem('daml.token');
    localStorage.removeItem('daml.party');
    setCredentials(undefined);
  }

  const httpBaseUrl = 'http://localhost:7575'; // JSON API endpoint

  if (!credentials) {
    return <LoginScreen onLogin={handleLogin} />;
  }

  return (
    <DamlLedger
      token={credentials.token}
      party={credentials.party}
      httpBaseUrl={httpBaseUrl}
    >
      <MainView onLogout={handleLogout} />
    </DamlLedger>
  );
};

const LoginScreen: React.FC<{ onLogin: (token: string, party: string) => void }> = ({ onLogin }) => {
  const [token, setToken] = useState('');
  const [party, setParty] = useState('');

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    onLogin(token, party);
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <h2>Canton Subscription Billing</h2>
        <p>Please log in to your Daml Ledger.</p>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="party">Party ID</label>
            <input
              id="party"
              type="text"
              value={party}
              onChange={(e) => setParty(e.target.value)}
              placeholder="Enter your Party ID"
              autoComplete="off"
            />
          </div>
          <div className="form-group">
            <label htmlFor="token">Auth Token (JWT)</label>
            <input
              id="token"
              type="password"
              value={token}
              onChange={(e) => setToken(e.target.value)}
              placeholder="Enter your JWT"
              autoComplete="off"
            />
          </div>
          <button type="submit" disabled={!token || !party}>
            Login
          </button>
        </form>
      </div>
    </div>
  );
};


const MainView: React.FC<{ onLogout: () => void }> = ({ onLogout }) => {
  const party = useParty();
  const ledger = useLedger();

  // --- Data Fetching using Stream Queries ---

  // Subscriptions where the current party is the merchant
  const { contracts: subsAsMerchant, loading: loadingMerchantSubs } = useStreamQueries(Subscription.Model, () => [{ merchant: party }]);

  // Subscriptions where the current party is the subscriber
  const { contracts: subsAsSubscriber, loading: loadingSubscriberSubs } = useStreamQueries(Subscription.Model, () => [{ subscriber: party }]);

  // All invoices visible to the current party
  const { contracts: allInvoices, loading: loadingInvoices } = useStreamQueries(Invoice.Model, () => [{}]);

  // All cancellation requests visible to the party
  const { contracts: cancellationRequests } = useStreamQueries(Cancellation.Request, () => [{}]);
  const activeCancellationCids = useMemo(() => new Set(cancellationRequests.map(c => c.payload.subscriptionCid)), [cancellationRequests]);

  // --- Event Handlers ---

  const handleCancelSubscription = async (subscriptionCid: ContractId<Subscription.Model>) => {
    try {
      await ledger.exercise(Subscription.Model.Request_Cancellation, subscriptionCid, {});
      alert('Cancellation request submitted successfully.');
    } catch (error) {
      console.error('Failed to request cancellation:', error);
      alert('Error: Could not submit cancellation request.');
    }
  };

  const loading = loadingMerchantSubs || loadingSubscriberSubs || loadingInvoices;

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>Subscription Dashboard</h1>
        <div className="user-info">
          <span>Logged in as: <strong>{party}</strong></span>
          <button onClick={onLogout}>Logout</button>
        </div>
      </header>
      <main className="app-main">
        {loading && <div className="loading-indicator">Loading data from ledger...</div>}

        {subsAsMerchant.length > 0 && (
          <section className="dashboard-section">
            <h2>Merchant View</h2>
            <p>You are the merchant for {subsAsMerchant.length} subscription(s).</p>
            <div className="card-grid">
              {subsAsMerchant.map(({ contractId, payload }) => (
                <div key={contractId} className="card subscription-card">
                  <h4>Subscription ID: {payload.subscriptionId}</h4>
                  <p><strong>Subscriber:</strong> {payload.subscriber}</p>
                  <p><strong>Amount:</strong> {payload.amount} {payload.currency}</p>
                  <p><strong>Interval:</strong> {payload.interval}</p>
                  <p><strong>Status:</strong> <span className={`status-badge status-${payload.status.toLowerCase()}`}>{payload.status}</span></p>
                </div>
              ))}
            </div>
          </section>
        )}

        {subsAsSubscriber.length > 0 && (
          <section className="dashboard-section">
            <h2>Subscriber View</h2>
            <p>You have {subsAsSubscriber.length} active subscription(s).</p>
            <div className="card-grid">
              {subsAsSubscriber.map(({ contractId, payload }) => (
                <div key={contractId} className="card subscription-card">
                  <h4>Subscription ID: {payload.subscriptionId}</h4>
                  <p><strong>Merchant:</strong> {payload.merchant}</p>
                  <p><strong>Amount:</strong> {payload.amount} {payload.currency}</p>
                  <p><strong>Next Billing:</strong> {new Date(payload.nextBillingDate).toLocaleDateString()}</p>
                  <p><strong>Status:</strong> <span className={`status-badge status-${payload.status.toLowerCase()}`}>{payload.status}</span></p>
                  <div className="card-actions">
                    {activeCancellationCids.has(contractId) ? (
                      <button className="action-btn-pending" disabled>Cancellation Pending</button>
                    ) : (
                      <button className="action-btn-danger" onClick={() => handleCancelSubscription(contractId)}>
                        Request Cancellation
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {subsAsMerchant.length === 0 && subsAsSubscriber.length === 0 && !loading && (
          <div className="empty-state">
            <h3>No Subscriptions Found</h3>
            <p>There are no active subscriptions for your party on the ledger.</p>
          </div>
        )}

        <section className="dashboard-section">
          <h2>Invoice History</h2>
          <InvoiceList invoices={allInvoices} />
        </section>
      </main>
    </div>
  );
};

export default App;